apiVersion: batch/v1
kind: CronJob
metadata:
  name: mav-cronjob
  namespace: stock
spec:
  schedule: "15 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mav-container
            image: artifacts.tekuro.io/mav-cronjob:latest
            env:
              - name: INFLUXDB_ORG
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secrets
                    key: org
              - name: INFLUXDB_URL
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secrets
                    key: url
              - name: INFLUXDB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secrets
                    key: token
              - name: INFLUXDB_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secrets
                    key: bucket
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
